blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/hetfs/luaOrbiter/discussions
    about: Ask questions, share ideas, or get help from the community.
